In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('species', axis = 1 )
y = df['species']

In [ ]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state = 42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_KNN = KNeighborsClassifier(n_neighbors = 13)

In [ ]:
model_KNN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [ ]:
model_KNN.score(X_test, y_test) #overfit

1.0

EXAMPLE OF SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_SVM = SVC(gamma = 'auto')

In [ ]:
model_SVM.fit(X_train, y_train)

SVC(gamma='auto')

In [ ]:
model_SVM.score(X_test, y_test)

1.0

NOW LETS USE THE GRID SEARCH CV (CROSS VALIDATION )

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_SVM),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
}, cv = 5, return_train_score = False)

In [ ]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00846229, 0.00365605, 0.00513654, 0.00353308, 0.00374813,
        0.00793648, 0.00611982, 0.00386214]),
 'std_fit_time': array([3.67452792e-03, 9.13165692e-05, 2.01210211e-03, 8.27235375e-05,
        1.74629161e-04, 5.10735230e-03, 2.96078055e-03, 1.05873528e-04]),
 'mean_score_time': array([0.00521278, 0.00280666, 0.00627394, 0.00264931, 0.00274405,
        0.00555878, 0.00463223, 0.00315795]),
 'std_score_time': array([1.57640575e-03, 9.31944039e-05, 3.19222777e-03, 4.94898625e-05,
        2.65606798e-04, 2.87467201e-03, 3.54161341e-03, 3.66211856e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008462,0.003675,0.005213,0.001576,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003656,0.000091,0.002807,0.000093,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005137,0.002012,0.006274,0.003192,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003533,0.000083,0.002649,0.000049,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.003748,0.000175,0.002744,0.000266,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.007936,0.005107,0.005559,0.002875,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.006120,0.002961,0.004632,0.003542,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.003862,0.000106,0.003158,0.000366,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

GRID SEARCH FOR K-NEAREST NEIGHBOURS

In [ ]:
classifier_KNN = GridSearchCV((model_KNN),{
    'n_neighbors' : [1,2,3,4,5,6,7,8,9,10],'weights':['uniform','distance'],
    'algorithm':['auto','ball_tree','kd_tree','brute']
}, cv = 5, return_train_score = False)

In [ ]:
classifier_KNN = classifier_KNN.fit(X,y)

In [ ]:
classifier_KNN

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'weights': ['uniform', 'distance']})

In [ ]:
classifier_KNN.cv_results_

{'mean_fit_time': array([0.00234203, 0.00201073, 0.00192456, 0.00184722, 0.00188141,
        0.00180745, 0.00182681, 0.00184283, 0.00187387, 0.0019331 ,
        0.00200362, 0.00197392, 0.00194278, 0.00189962, 0.00185966,
        0.00182028, 0.00187521, 0.00185223, 0.00230994, 0.00205302,
        0.00203657, 0.00197568, 0.00288596, 0.00295486, 0.00311732,
        0.00292487, 0.00296607, 0.00323462, 0.00312896, 0.00267057,
        0.00275402, 0.0025806 , 0.00258799, 0.00272093, 0.00255723,
        0.00255752, 0.00255213, 0.00281706, 0.00264287, 0.00262003,
        0.0025661 , 0.00254045, 0.00264692, 0.0026845 , 0.0025805 ,
        0.00283575, 0.00259228, 0.00252843, 0.00274611, 0.00280805,
        0.002916  , 0.00258865, 0.00260997, 0.00301967, 0.00276933,
        0.0026125 , 0.00263548, 0.00265951, 0.0026145 , 0.00316949,
        0.00253859, 0.00237064, 0.0025136 , 0.00254431, 0.00242724,
        0.00245914, 0.00247955, 0.00239301, 0.00252686, 0.00251107,
        0.00267749, 0.002742  , 0.0028594 , 0.00276041, 0.0025166 ,
        0.00341759, 0.00251904, 0.00253992, 0.00253382, 0.00262437]),
 'std_fit_time': array([3.57742654e-04, 8.26990989e-05, 6.09998303e-05, 2.99905175e-05,
        2.14764195e-05, 5.12629885e-05, 4.79285155e-05, 5.95066409e-05,
        6.61788479e-05, 6.31921686e-05, 4.48610770e-05, 1.35703817e-04,
        1.52939198e-04, 2.52798357e-05, 4.33439469e-05, 5.96533386e-05,
        4.01454411e-05, 6.82426112e-05, 2.19322680e-04, 2.08041599e-04,
        1.81774615e-04, 7.73856319e-05, 4.21611439e-04, 1.54264124e-04,
        2.57346456e-04, 9.78096813e-05, 1.51353447e-04, 6.61715843e-04,
        2.36114835e-04, 1.32020822e-04, 2.18959521e-04, 4.06561775e-05,
        5.62232059e-05, 1.99133991e-04, 2.91384509e-04, 3.30073280e-05,
        4.75271994e-05, 2.12099805e-04, 7.64187150e-05, 5.89925619e-05,
        6.41391178e-05, 5.99398912e-05, 6.89378571e-05, 6.84336249e-05,
        6.25139879e-05, 3.99319107e-04, 9.37734430e-05, 5.20655085e-05,
        1.84160350e-04, 3.39761061e-04, 4.39613283e-04, 7.92968295e-05,
        5.23477296e-05, 2.27977316e-04, 1.17956213e-04, 8.34136081e-05,
        1.77934519e-04, 1.39299911e-04, 4.34427177e-05, 6.32401196e-04,
        1.38404365e-04, 2.63455874e-05, 1.40560029e-04, 8.00746607e-05,
        3.17627241e-05, 3.99060571e-05, 9.98077241e-05, 3.22311586e-05,
        6.62365432e-05, 1.00309176e-04, 2.02417312e-04, 1.61677079e-04,
        2.35445048e-04, 1.63306876e-04, 2.32609093e-04, 8.38910667e-04,
        5.07343532e-05, 1.44298157e-04, 2.24636239e-04, 2.85290943e-04]),
 'mean_score_time': array([0.00416002, 0.00231433, 0.00268335, 0.0026423 , 0.00268531,
        0.00211835, 0.00262136, 0.00231071, 0.00282502, 0.00242448,
        0.00284061, 0.002244  , 0.00291924, 0.00216246, 0.00273857,
        0.00208325, 0.00274811, 0.00214257, 0.00321779, 0.00231743,
        0.0028307 , 0.00220695, 0.00478673, 0.00337372, 0.00408459,
        0.00328612, 0.00411701, 0.00360422, 0.00485368, 0.00306358,
        0.00404959, 0.0028583 , 0.00365205, 0.0033535 , 0.00388021,
        0.0029223 , 0.00372596, 0.00316978, 0.00378118, 0.00290442,
        0.00365319, 0.00286088, 0.00386119, 0.00292497, 0.00391359,
        0.00296421, 0.00370259, 0.00287905, 0.00372515, 0.00362887,
        0.0038815 , 0.00297818, 0.00374589, 0.00343862, 0.00396724,
        0.00294051, 0.00384426, 0.00295334, 0.00380816, 0.00329657,
        0.01495805, 0.00275192, 0.0039989 , 0.00303397, 0.0035707 ,
        0.00281744, 0.00372019, 0.00282955, 0.00391445, 0.00297036,
        0.00394707, 0.00340152, 0.00442281, 0.0033257 , 0.00422888,
        0.00337467, 0.00379591, 0.00314898, 0.00394235, 0.0030458 ]),
 'std_score_time': array([1.94020787e-03, 1.88801323e-04, 6.94832735e-05, 8.96570657e-04,
        8.81755587e-05, 5.37516260e-05, 3.69785295e-05, 2.28389986e-04,
        2.08267220e-04, 1.35334585e-04, 1.00564787e-04, 7.62287994e-05,
        4.41396374e-04, 4.74267233e-05, 2.30399702e-05, 5.19339809e-05,
        1.29086838e-04, 7.74798904e-05, 2.12268794e-04, 1.55695547e-04,
        6.05486314e-05, 9.82549085e-05, 1.20035828e-03, 3.53442452e-04,
        1.55990264e-04, 6.08618705e-05, 3.41751324e-04, 7.70160704e-04,
        8.85805662e-04, 1.89390607e-04, 2.82028376e-04, 4.16979304e-05,
        8.64268369e-05, 6.52246385e-04, 1.51474467e-04, 6.91134298e-05,
        2.00780404e-04, 1.66137415e-04, 7.54005457e-05, 2.76158296e-05,
        8.59543916e-05, 1.36278742e-04, 4.21661682e-04, 1.24382166e-04,
        2.69466471e-04, 1.52333868e-04, 1.04546957e-04, 1.03905279e-04,
        1.13726872e-04, 9.79435300e-04, 1.71630605e-04, 7.87296416e-05,
        6.84960603e-05, 5.39238245e-04, 1.87222409e-04, 5.14086188e-05,
        3.30635392e-04, 1.30723618e-04, 1.18077686e-04, 3.83550257e-04,
        2.25117940e-02, 7.51557384e-05, 3.14836319e-04, 2.73682248e-04,
        4.18579380e-05, 4.63444017e-05, 8.12481545e-05, 3.56114683e-05,
        1.62280485e-04, 1.15075893e-04, 1.87026111e-04, 6.57291493e-04,
        2.91215957e-04, 5.82634365e-04, 2.40185835e-04, 1.71848870e-04,
        4.29625781e-05, 1.74146806e-04, 2.29512310e-04, 1.96913944e-04]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9,
                    10, 10, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8,
                    9, 9, 10, 10, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7,
                    8, 8, 9, 9, 10, 10, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6,
                    7, 7, 8, 8, 9, 9, 10, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 2, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 2, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 4, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 4, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 6, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 6, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 8, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 8, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 4, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 4, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 6, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 6, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 8, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 8, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 4, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 4, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 6, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 6, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 8, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 8, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 2, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 2, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 3, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 4, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 4, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 6, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 6, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 8, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 8, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 9, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 10, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.9       ,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.9       , 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.93333333, 0.9       , 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,

In [ ]:
results = pd.DataFrame(classifier_KNN.cv_results_)

In [ ]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002342,0.000358,0.004160,0.001940,auto,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,65
1,0.002011,0.000083,0.002314,0.000189,auto,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,65
2,0.001925,0.000061,0.002683,0.000069,auto,2,uniform,"{'algorithm': 'auto', 'n_neighbors': 2, 'weigh...",0.966667,0.933333,0.933333,0.900000,1.0,0.946667,0.033993,77
3,0.001847,0.000030,0.002642,0.000897,auto,2,distance,"{'algorithm': 'auto', 'n_neighbors': 2, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,65
4,0.001881,0.000021,0.002685,0.000088,auto,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 3, 'weigh...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,0.003418,0.000839,0.003375,0.000172,brute,8,distance,"{'algorithm': 'brute', 'n_neighbors': 8, 'weig...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,6
76,0.002519,0.000051,0.003796,0.000043,brute,9,uniform,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,6
77,0.002540,0.000144,0.003149,0.000174,brute,9,distance,"{'algorithm': 'brute', 'n_neighbors': 9, 'weig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,29
78,0.002534,0.000225,0.003942,0.000230,brute,10,uniform,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
79,0.002624,0.000285,0.003046,0.000197,brute,10,distance,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1

In [ ]:
results[['param_algorithm',	'param_n_neighbors','param_weights','mean_test_score'	]]

   param_algorithm  param_n_neighbors param_weights  mean_test_score
0             auto                  1       uniform         0.960000
1             auto                  1      distance         0.960000
2             auto                  2       uniform         0.946667
3             auto                  2      distance         0.960000
4             auto                  3       uniform         0.966667
..             ...                ...           ...              ...
75           brute                  8      distance         0.980000
76           brute                  9       uniform         0.980000
77           brute                  9      distance         0.973333
78           brute                 10       uniform         0.986667
79           brute                 10      distance         0.986667

[80 rows x 4 columns]

RANDOMIZED SEARCH CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_SVM),{
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
},n_iter = 10, cv = 5, return_train_score = False)

In [ ]:
classifier_r.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results_randomized = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results_randomized

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002930,0.000839,0.001910,0.000324,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002401,0.000147,0.001720,0.000034,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002681,0.000195,0.002026,0.000189,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002350,0.000309,0.001812,0.000166,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002280,0.000036,0.001662,0.000025,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002128,0.000023,0.001605,0.000017,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002261,0.000119,0.001642,0.000029,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002141,0.000045,0.001599,0.000017,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results_randomized[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000