In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
df= pd.read_csv('train.txt', sep = ';', header = None, names = ['text','emotion'])

In [70]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [71]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [72]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

Here We are doing all the Emotions converts in the form of Numbers like sadness = 0, anger = 1 and etc .

In [73]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i += 1
df['emotion'] = df['emotion'].map(emotion_numbers)

In [74]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

1. Coverts all the Captical letter into small letter ( lowercase)

In [63]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [62]:
df['text']

0
1
2
3
4
        ..
15995
15996
15997
15998
15999
Name: text, Length: 16000, dtype: object

2. Remove Punctuation ( ! , @ , #, #, $, %, &, *)
But in deep learning (BERT, GPT) Its Important

In [44]:
import string

def remove_punctuation(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [45]:
df['text'] = df['text'].apply(remove_punctuation)

In [46]:
df['text']

0                                  i didnt feel humiliated
1        i can go from feeling so hopeless to so damned...
2         im grabbing a minute to post i feel greedy wrong
3        i am ever feeling nostalgic about the fireplac...
4                                     i am feeling grouchy
                               ...
15995    i just had a very brief time in the beanbag an...
15996    i am now turning and i feel pathetic that i am...
15997                       i feel strong and good overall
15998    i feel like this was such a rude comment and i...
15999    i know a lot but i feel so stupid because i ca...
Name: text, Length: 16000, dtype: object

3. Remove Digit from the text (optional - depends on task)

In [47]:
def remove_numbers(txt):
  new = " "
  for i in txt:
    if not i.isdigit():
      new = new+i

  return new
df['text'] = df['text'].apply(remove_numbers)

4. Remove URLS and links

5. Remove Emoji

In [48]:
def remove_emojis(txt):
  new = " "
  for i in txt:
    if not i.isdigit():
      new = new+i
    return new
df['text'] = df['text'].apply(remove_emojis)

7. Remove Stopwords

CORPUS = Collection of text

SENTENCE = A group of words that forms a meaningful Statement

TOKEN = 'I' 'LOVE' 'U'

Remove stopwords we have to preprocesses the data and here we import nltk

In [49]:
import nltk

In [50]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [18]:
nltk.download("punkt") #punctuation tokenization
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [51]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [52]:
len(stop_words)

198

In [53]:
df.loc[1]

text
emotion     0
Name: 1, dtype: object

In [54]:
df.loc[1]['text']

'  '

# Remove the Stopwords

In [55]:
def remove(txt):
  word = txt.split()
  cleaned = []
  for i in word:
    if i not in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [79]:
df['text'] = df['text'].apply(remove)

In [78]:
df.iloc[1, df.columns.get_loc('text')]

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [75]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [80]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size  = 0.20, random_state=42)

In [81]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [82]:
df.shape

(16000, 2)

In [83]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer#bags of words

In [84]:
Bag_of_words = CountVectorizer()

In [88]:
X_train_bow = Bag_of_words.fit_transform(X_train)

X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116059 stored elements and shape (12800, 13361)>

In [89]:
X_test_bow = Bag_of_words.fit_transform(X_test)

In [90]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 28719 stored elements and shape (3200, 6175)>

Multinomial Naive Bayes = These is for Naive Bayes Classifier

In [91]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [92]:
nb_model = MultinomialNB()

In [95]:
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [98]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.768125

In [100]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0])

In [101]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

Same for  TF-IDF we will calculate

In [118]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.768125

In [119]:
y_pred = nb2_model.predict(X_test_tfidf)

In [120]:
print(accuracy_score(y_test, y_pred))

0.6609375

Once Logistic Regression

In [133]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [136]:
accuracy_score(y_test, logistic_model.predict(X_test_tfidf))

0.8628125