In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("/content/StudentPerformanceFactors.csv")
print(df.head())

   Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0             23          84                  Low                High
1             19          64                  Low              Medium
2             24          98               Medium              Medium
3             29          89                  Low              Medium
4             19          92               Medium              Medium

  Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level  \
0                         No            7               73              Low
1                         No            8               59              Low
2                        Yes            7               91           Medium
3                        Yes            8               98           Medium
4                        Yes            6               65           Medium

  Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality  \
0             Yes                  0           Low          Medium
1             Yes                  2        Medium          Medium
2             Yes                  2        Medium          Medium
3             Yes                  1        Medium          Medium
4             Yes                  3        Medium            High

  School_Type Peer_Influence  Physical_Activity Learning_Disabilities  \
0      Public       Positive                  3                    No
1      Public       Negative                  4                    No
2      Public        Neutral                  4                    No
3      Public       Negative                  4                    No
4      Public        Neutral                  4                    No

  Parental_Education_Level Distance_from_Home  Gender  Exam_Score
0              High School               Near    Male          67
1                  College           Moderate  Female          61
2             Postgraduate               Near    Male          74
3              High School           Moderate    Male          71
4                  College               Near  Female          70

In [4]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [5]:
print(df.shape)

(6607, 20)

In [6]:
print(df.isnull().sum())

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [7]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

print("Numerical:", num_cols)
print("Categorical:", cat_cols)

Numerical: Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score'],
      dtype='object')
Categorical: Index(['Parental_Involvement', 'Access_to_Resources',
       'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access',
       'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence',
       'Learning_Disabilities', 'Parental_Education_Level',
       'Distance_from_Home', 'Gender'],
      dtype='object')

In [8]:
#Handles missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df[num_cols] = imputer.fit_transform(df[num_cols])

In [9]:
# Handles categorical missing values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'most_frequent')
df[cat_cols] = imputer.fit_transform(df[cat_cols])

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

In [12]:
df[col]

0       1
1       0
2       1
3       1
4       0
       ..
6602    0
6603    0
6604    0
6605    0
6606    1
Name: Gender, Length: 6607, dtype: int64

In [13]:
# Instead of using these we can use pd.get_dummies
# df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [14]:
print("Total Missing:", df.isnull().sum().sum())
print(df.head())

Total Missing: 0
   Hours_Studied  Attendance  Parental_Involvement  Access_to_Resources  \
0           23.0        84.0                     1                    0
1           19.0        64.0                     1                    2
2           24.0        98.0                     2                    2
3           29.0        89.0                     1                    2
4           19.0        92.0                     2                    2

   Extracurricular_Activities  Sleep_Hours  Previous_Scores  Motivation_Level  \
0                           0          7.0             73.0                 1
1                           0          8.0             59.0                 1
2                           1          7.0             91.0                 2
3                           1          8.0             98.0                 2
4                           1          6.0             65.0                 2

   Internet_Access  Tutoring_Sessions  Family_Income  Teacher_Quality  \
0                1                0.0              1                2
1                1                2.0              2                2
2                1                2.0              2                2
3                1                1.0              2                2
4                1                3.0              2                0

   School_Type  Peer_Influence  Physical_Activity  Learning_Disabilities  \
0            1               2                3.0                      0
1            1               0                4.0                      0
2            1               1                4.0                      0
3            1               0                4.0                      0
4            1               1                4.0                      0

   Parental_Education_Level  Distance_from_Home  Gender  Exam_Score
0                         1                   2       1        67.0
1                         0                   1       0        61.0
2                         2                   2       1        74.0
3                         1                   1       1        71.0
4                         0                   2       0        70.0

Label Encoding

Categorical text ko numbers me covert when jab column binary ho (Sirf 2 values) Male, female yes , no .

ONE - HOT ENCODING
1 Column ko multiple 0/1 columns me todna
Motivation = low,  Medium ,  High  ( 1, 0 , 0 )

Standard Scaler

numerical values ko scale karta hai mean = 0 and standard deviation = 1

LABEL ENCODING

In [15]:
from sklearn.preprocessing import LabelEncoder

binary_cols = ['Gender', 'Internet_Access', 'Learning_Disabilities']
le = LabelEncoder()
for col in binary_cols:
    df[col] = le.fit_transform(df[col])
    print(df[col])

0       1
1       0
2       1
3       1
4       0
       ..
6602    0
6603    0
6604    0
6605    0
6606    1
Name: Gender, Length: 6607, dtype: int64
0       1
1       1
2       1
3       1
4       1
       ..
6602    1
6603    1
6604    1
6605    1
6606    1
Name: Internet_Access, Length: 6607, dtype: int64
0       0
1       0
2       0
3       0
4       0
       ..
6602    0
6603    0
6604    0
6605    0
6606    0
Name: Learning_Disabilities, Length: 6607, dtype: int64

ONE - HOT ENCODING (MULTI- CATEGORY)

In [16]:
cat_cols = [
    'Parental_Involvement',
    'Access_to_Resources',
    'Extracurricular_Activities',
    'Motivation_Level',
    'Family_Income',
    'Teacher_Quality',
    'School_Type',
    'Peer_Influence',
    'Parental_Education_Level'
]

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [17]:
print(df.columns.tolist())

['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores', 'Internet_Access', 'Tutoring_Sessions', 'Physical_Activity', 'Learning_Disabilities', 'Distance_from_Home', 'Gender', 'Exam_Score', 'Parental_Involvement_1', 'Parental_Involvement_2', 'Access_to_Resources_1', 'Access_to_Resources_2', 'Extracurricular_Activities_1', 'Motivation_Level_1', 'Motivation_Level_2', 'Family_Income_1', 'Family_Income_2', 'Teacher_Quality_1', 'Teacher_Quality_2', 'School_Type_1', 'Peer_Influence_1', 'Peer_Influence_2', 'Parental_Education_Level_1', 'Parental_Education_Level_2']

Stanadard Scaling

In [18]:
from sklearn.preprocessing import StandardScaler

num_cols = [
    'Hours_Studied',
    'Attendance',
    'Sleep_Hours',
    'Previous_Scores',
    'Tutoring_Sessions',
    'Physical_Activity'
]


scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [19]:
df[num_cols]

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity
0,0.504942,0.348375,-0.019796,-0.143800,-1.213934,0.031411
1,-0.162822,-1.383736,0.661399,-1.116110,0.411451,1.001199
2,0.671882,1.560853,-0.019796,1.106313,0.411451,1.001199
3,1.506587,0.781403,0.661399,1.592469,-0.401242,1.001199
4,-0.162822,1.041220,-0.700990,-0.699406,1.224144,1.001199
...,...,...,...,...,...,...
6602,0.838823,-0.950708,-0.019796,0.064552,-0.401242,-0.938377
6603,0.504942,-0.344469,0.661399,0.411806,1.224144,-0.938377
6604,0.004119,0.868009,-0.700990,-0.699406,1.224144,-0.938377
6605,-1.665291,0.521587,-0.700990,1.106313,0.411451,0.031411
6606,-0.830586,-1.123919,1.342594,1.314666,-1.213934,1.001199

In [20]:
from sklearn.model_selection import train_test_split

#Features and target
X = df.drop('Exam_Score', axis = 1)
y = df['Exam_Score']

#split 80% train , 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

LINEAR REGRESSION

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [22]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [23]:
y_pred = model.predict(X_test)

In [24]:
print("Linear Regression")
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

Linear Regression
R2 Score: 0.7701156377221374
MAE: 0.4510919332848635

In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

rf_model = RandomForestRegressor(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print("Random Forest Regression")
print("Random Forest R2: ", r2_score(y_test, y_pred))
print("Random Forest MAE: ", mean_absolute_error(y_test, y_pred))

Random Forest Regression
Random Forest R2:  0.650757543329647
Random Forest MAE:  1.161089258698941

In [26]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(n_estimators=200, learning_rate=0.05, random_state=42)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

print("XGBoost Regression")
print("XGBoost R2: ", r2_score(y_test, y_pred))
print("XGBoost MAE: ", mean_absolute_error(y_test, y_pred))

print("XGBoost Regresss")

XGBoost Regression
XGBoost R2:  0.7184050177723276
XGBoost MAE:  0.8097834190334026
XGBoost Regresss

MAE is the average absolute difference between actual values and predicted values. Model on average kitna galat predict kar raha hai.

Here We Perform Supervised Learning and In the Supervised learning We have Regressions so here we perfrom Matrices R2, MAE.

Now Lets Perform Unsupervised Learning.

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

In [28]:
df.columns
print(df.head())

   Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  Internet_Access  \
0       0.504942    0.348375    -0.019796        -0.143800                1
1      -0.162822   -1.383736     0.661399        -1.116110                1
2       0.671882    1.560853    -0.019796         1.106313                1
3       1.506587    0.781403     0.661399         1.592469                1
4      -0.162822    1.041220    -0.700990        -0.699406                1

   Tutoring_Sessions  Physical_Activity  Learning_Disabilities  \
0          -1.213934           0.031411                      0
1           0.411451           1.001199                      0
2           0.411451           1.001199                      0
3          -0.401242           1.001199                      0
4           1.224144           1.001199                      0

   Distance_from_Home  Gender  ...  Motivation_Level_2  Family_Income_1  \
0                   2       1  ...               False             True
1                   1       0  ...               False            False
2                   2       1  ...                True            False
3                   1       1  ...                True            False
4                   2       0  ...                True            False

   Family_Income_2  Teacher_Quality_1  Teacher_Quality_2  School_Type_1  \
0            False              False               True           True
1             True              False               True           True
2             True              False               True           True
3             True              False               True           True
4             True              False              False           True

   Peer_Influence_1  Peer_Influence_2  Parental_Education_Level_1  \
0             False              True                        True
1             False             False                       False
2              True             False                       False
3             False             False                        True
4              True             False                       False

   Parental_Education_Level_2
0                       False
1                       False
2                        True
3                       False
4                       False

[5 rows x 27 columns]

In [37]:
df = df.replace({True:1, False:0})

In [38]:
print(df.head())

   Hours_Studied  Attendance  Sleep_Hours  Previous_Scores  Internet_Access  \
0       0.504942    0.348375    -0.019796        -0.143800                1
1      -0.162822   -1.383736     0.661399        -1.116110                1
2       0.671882    1.560853    -0.019796         1.106313                1
3       1.506587    0.781403     0.661399         1.592469                1
4      -0.162822    1.041220    -0.700990        -0.699406                1

   Tutoring_Sessions  Physical_Activity  Learning_Disabilities  \
0          -1.213934           0.031411                      0
1           0.411451           1.001199                      0
2           0.411451           1.001199                      0
3          -0.401242           1.001199                      0
4           1.224144           1.001199                      0

   Distance_from_Home  Gender  ...  Motivation_Level_2  Family_Income_1  \
0                   2       1  ...                   0                1
1                   1       0  ...                   0                0
2                   2       1  ...                   1                0
3                   1       1  ...                   1                0
4                   2       0  ...                   1                0

   Family_Income_2  Teacher_Quality_1  Teacher_Quality_2  School_Type_1  \
0                0                  0                  1              1
1                1                  0                  1              1
2                1                  0                  1              1
3                1                  0                  1              1
4                1                  0                  0              1

   Peer_Influence_1  Peer_Influence_2  Parental_Education_Level_1  \
0                 0                 1                           1
1                 0                 0                           0
2                 1                 0                           0
3                 0                 0                           1
4                 1                 0                           0

   Parental_Education_Level_2
0                           0
1                           0
2                           1
3                           0
4                           0

[5 rows x 27 columns]

In [39]:
inertia = []
for k in range (2,9):
  model_KMeans = KMeans(n_clusters=k, random_state=42)
  model.fit(num_cols)
  inertia.append(model.inertia_)

TypeError: LinearRegression.fit() missing 1 required positional argument: 'y'